//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceToSocket
    {
        public int IdSocket { get; set; }
        public int IdDevice { get; set; }
        public int Count { get; set; }
        public int Id { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Sockets Sockets { get; set; }
    }
}
