//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceToSocket
    {
        public int IdSocket { get; set; }
        public int IdDevice { get; set; }
        public int Count { get; set; }
        public int Id { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Sockets Sockets { get; set; }
    }
}
