//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Characteristic> Characteristic { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Entities> Entities { get; set; }
        public virtual DbSet<Sockets> Sockets { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<DeviceToSocket> DeviceToSocket { get; set; }
        public virtual DbSet<DeviceToType> DeviceToType { get; set; }
    }
}
